import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { validateStory } from '../../scripts/validate-project-story.mjs';

const source = JSON.parse(readFileSync('evidence/simulation/project-story.json', 'utf8'));
const mutate = (fn) => { const copy = structuredClone(source); fn(copy); return validateStory(copy, { checkFiles: false }); };
const has = (errors, code) => assert.equal(errors.some((error) => error.startsWith(`${code}:`)), true, code);
const task = (story) => story.tickets.find((ticket) => ticket.type === 'task');
const worklog = (story, target = task(story), hours = 1) => ({ id:`WL-${target.id}-TEST`, taskId:target.id, date:'2026-07-13', role:'Lead BC Consultant', actorRef:'P-PILOT-LEAD-001', actorType:'human', actionRole:'Lead BC Consultant', hours, activity:`Prüfbarer Test-Worklog für ${target.id}`, phase:target.phase, billable:true, hourlyRate:120, netAmount:hours*120 });
const addDynamicTask = (story) => { const template=structuredClone(task(story)); const parent=story.tickets.find((ticket)=>ticket.id===template.parent); template.id='UABC-999'; template.code='UABC-999'; template.summary='Zusätzliche fachlich begründete Prüfarbeit planen.'; template.description='Eine zusätzliche fachlich begründete Prüfarbeit wird als dynamische Erweiterung geplant und bleibt bis zur passenden Evidence offen.'; template.status='created'; template.statusHistory=[{status:'created',time:'2026-07-13',actorRef:'P-PILOT-LEAD-001',actorType:'human',actionRole:'Projektleitung'}]; template.acceptanceCriteria=[{criterion:'Die zusätzliche Prüfarbeit UABC-999 besitzt einen klaren fachlichen Umfang.',fulfilled:false},{criterion:'UABC-999 wird erst nach konkretem Readback und Evidence abgeschlossen.',fulfilled:false}]; template.comments=[{...template.comments[0],id:'COM-UABC-999-CURRENT-PLAN',text:'UABC-999 ist fachlich geplant und noch nicht ausgeführt.'}]; template.worklogs=[];template.actualHours=0;template.netAmount=0;template.worklogHours=0;template.dependencies=[];template.childTicketIds=[]; parent.childTicketIds.push(template.id); story.tickets.push(template); story.controls.activeTicketCount+=1; story.controls.taskCount+=1; story.controls.billableTicketCount+=1; };

test('positive Vollstory besteht', () => assert.deepEqual(validateStory(source, { checkFiles: true }), []));
test('NESTED_TYPE erkennt Worklogtyp', () => has(mutate((s) => { const t=task(s);t.worklogs=[worklog(s,t)];t.worklogs[0].hours='6'; }), 'WORKLOG-NESTED-TYP'));
test('UNAUTHORIZED_PROPERTY erkennt unerlaubte Top-Level-Eigenschaft', () => has(mutate((s) => { s.unexpected = true; }), 'UNERLAUBTE-EIGENSCHAFT'));
test('CLOSING_COMMENT erkennt fehlenden Abschlusskommentar', () => has(mutate((s) => { task(s).comments.pop(); }), 'ABSCHLUSS-KOMMENTAR-FEHLT'));
test('WORKLOG_SUM erkennt falsche dynamische Istsumme', () => has(mutate((s) => { s.controls.actualHours=7; }), 'WORKLOG-SUMME'));
test('STATUS_TIME_TRAVEL erkennt zeitliche Rückreise', () => has(mutate((s) => { task(s).closedAt = '2020-01-01'; }), 'STATUS-ZEITREISE'));
test('TERMINAL_STATUS erkennt abweichenden Endstatus', () => has(mutate((s) => { s.tickets[0].statusHistory[s.tickets[0].statusHistory.length - 1] = 'closed'; }), 'ENDSTATUS-ABWEICHUNG'));
test('PAGE_CYCLE erkennt Seitenzyklus', () => has(mutate((s) => { s.pages.find((p) => p.id === 'PAGE-UABC-130').parent = 'PAGE-UABC-050'; }), 'SEITE-ZYKLUS'));
test('PAGE_METADATA erkennt verschachtelten Metadatenfehler', () => has(mutate((s) => { s.pages[0].version = '3'; }), 'SEITE-METADATEN-TYP'));
test('UNKNOWN_TIMELINE_REFERENCE erkennt unbekannte Ticketreferenz', () => has(mutate((s) => { s.timeline[0].tickets = ['TKT-NOT-FOUND']; }), 'UNBEKANNTE-TIMELINE-REFERENZ'));
test('OPEN_P1_P2 erkennt unzulässigen BC-Ausführungsclaim', () => has(mutate((s) => { s.controls.realBcExecution = true; }), 'OFFENES-P1-P2'));
test('UNKNOWN_RELATION erkennt unbekannten Relationstyp', () => has(mutate((s) => { s.relations = [{ type: 'unknown', from: 'TKT-UABC-22', to: 'TKT-UABC-23', inverse: 'TKT-UABC-23->TKT-UABC-22' }]; }), 'UNBEKANNTE-RELATION'));
test('INVERSE_RELATION erkennt falsche inverse Kante', () => has(mutate((s) => { s.relations = [{ type: 'blocks', from: 'TKT-UABC-22', to: 'TKT-UABC-23', inverse: 'wrong' }]; }), 'INVERSE-RELATION'));
test('DUPLICATE_SOURCE_PATH erkennt echten doppelten Quellpfad', () => has(mutate((s) => { s.pages[2].sourcePath = s.pages[1].sourcePath; }), 'SEITE-DOPPELTER-PFAD'));
test('NESTED_ADDITIONAL_PROPERTY erkennt unerlaubte Kommentareigenschaft', () => has(mutate((s) => { task(s).comments[0].unexpected = true; }), 'UNERLAUBTE-EIGENSCHAFT'));
test('PAGE_FILE_METADATA erkennt Abweichung aus injiziertem Leser', () => has(validateStory(source, { checkFiles: false, metadataReader: () => ({ id: 'falsch', parent: null, version: 99, status: 'falsch' }) }), 'SEITE-METADATEN-ABWEICHUNG'));
test('STATUSHISTORY_TIME_TRAVEL erkennt Zeitreise in strukturierter Historie', () => has(mutate((s) => { s.tickets[0].statusHistory = [{ status: 'created', time: '2026-08-20' }, { status: 'in-progress', time: '2026-08-19' }, { status: 'done', time: '2026-08-20' }]; }), 'STATUSHISTORY-ABWEICHUNG'));
test('WORKLOG_COST erkennt falsche globale Kosten', () => has(mutate((s) => { s.offer.actual_cost = 120; }), 'WORKLOG-SUMME'));
test('TIMELINE_UNKNOWN_EVIDENCE erkennt unbekannte Evidence', () => has(mutate((s) => { s.timeline[0].evidence = 'EVIDENCE-NOT-FOUND'; }), 'UNBEKANNTE-TIMELINE-REFERENZ'));
test('TIMELINE_UNKNOWN_SESSION erkennt unbekannte BC-Sitzung', () => has(mutate((s) => { s.timeline[0].sessions = ['SESSION-NOT-FOUND']; }), 'UNBEKANNTE-TIMELINE-REFERENZ'));
test('TIMELINE_UNKNOWN_DECISION erkennt unbekannte Entscheidung', () => has(mutate((s) => { s.timeline[0].decision = 'DECISION-NOT-FOUND'; }), 'UNBEKANNTE-TIMELINE-REFERENZ'));
test('TIMELINE_OUTSIDE_WINDOW erkennt Zeit vor aktuellem Projektstart', () => has(mutate((s) => { s.timeline[0].time = '2026-07-12'; }), 'TIMELINE-GRENZE'));
test('REFERENCED_OPEN_P1 blockiert fälschlich geschlossene Hypercare', () => has(mutate((s) => { s.hypercare[0].status='closed';s.hypercare[0].retest='passed'; }), 'FUTURE-GATE-STATUS'));
test('INVERSE_MISSING erkennt fehlende Rückkante', () => has(mutate((s) => { s.relations = s.relations.filter((r) => !(r.type === 'references' && r.from === 'UABC-32')); }), 'INVERSE-RELATION'));
test('STRING_STATUSHISTORY wird nicht als kanonisch akzeptiert', () => has(mutate((s) => { s.tickets[0].statusHistory = ['created','in-progress','done']; }), 'STATUSHISTORY-ABWEICHUNG'));
test('FEHLENDE_WORKLOG_KOSTEN werden abgelehnt', () => has(mutate((s) => { const t=task(s);t.worklogs=[worklog(s,t)];delete t.worklogs[0].netAmount; }), 'WORKLOG-NESTED-TYP'));
test('FEHLENDE_HYPERCARE_EVIDENCE wird abgelehnt', () => has(mutate((s) => { delete s.hypercare[0].evidence; }), 'HYPERCARE-RECORD'));
test('GRAPH_WAISE erkennt eine unbekannte Domänenkante', () => has(mutate((s) => { s.relations.push({ type: 'references', from: 'PAGE-NOT-FOUND', to: 'TKT-UABC-22' }); }), 'RELATION-WAISE'));
test('GRAPH_DUPLIKAT erkennt doppelte Kante', () => has(mutate((s) => { s.relations.push(structuredClone(s.relations[0])); }), 'RELATION-DOPPELT'));
test('PAGE_SPACE erkennt fehlende Space-Zuordnung', () => has(mutate((s) => { delete s.pages[0].spaceId; }), 'SEITE-METADATEN-TYP'));
test('PAGE_SPACE_PARENT erkennt Space-uebergreifenden Parent', () => has(mutate((s) => { s.pages.find((p) => p.id === 'PAGE-UABC-010').parent = 'PAGE-UABC-090'; }), 'SEITE-SPACE-PARENT'));
test('PAGE_ORDER erkennt doppelte Reihenfolge im Space', () => has(mutate((s) => { s.pages.find((p) => p.id === 'PAGE-UABC-010').order = 0; }), 'SEITE-REIHENFOLGE'));
test('PAGE_ROOT erkennt fehlende deklarierte Space-Wurzel', () => has(mutate((s) => { s.pages.find((p) => p.id === 'PAGE-UABC-090').parent = 'PAGE-UABC-000'; }), 'SEITE-WURZEL'));
test('TICKET_TYPE_MISSING erkennt fehlenden kanonischen Typ', () => has(mutate((s) => { delete s.tickets[0].type; }), 'TICKET-TYP'));
test('TICKET_TYPE_UNKNOWN erkennt unbekannten kanonischen Typ', () => has(mutate((s) => { s.tickets[0].type = 'ableitung-aus-titel'; }), 'TICKET-TYP'));
test('TICKET_PARENT_TYPE erkennt inkonsistenten Parent-Typ', () => has(mutate((s) => { s.tickets.find((t) => t.id === 'UABC-34').parent = 'UABC-47'; }), 'TICKET-PARENT-TYP'));
test('TICKET_PARENT_TYPE erkennt Parent an Epic', () => has(mutate((s) => { s.tickets[0].parent = 'UABC-50'; }), 'TICKET-PARENT-TYP'));
test('ELTERN_WORKLOG blockiert fakturierbaren Worklog auf Epic', () => has(mutate((s) => { s.tickets[0].worklogs = [worklog(s)]; }), 'ELTERN-WORKLOG'));
test('TASK_BILLABLE blockiert nicht abrechenbaren Phasen-Task', () => has(mutate((s) => { task(s).billable = false; }), 'TASK-ABRECHNUNG'));
test('TASK_PARENT blockiert Task ohne Story- oder Bug-Elternteil', () => has(mutate((s) => { task(s).parent = 'UABC-4'; }), 'TICKET-PARENT-TYP'));
test('DOPPELTES nicht gebundenes WORKLOG wird blockiert', () => has(mutate((s) => { const t=task(s);t.worklogs=[worklog(s,t),{...worklog(s,t),id:`WL-${t.id}-TEST-2`}]; }), 'TASK-ABRECHNUNG'));
test('HYPERCARE_GRENZE blockiert Ist über Ticketschätzung', () => has(mutate((s) => { const t=s.tickets.find((x)=>x.id==='UABC-47');const hours=t.estimateHours+1;t.worklogs=[worklog(s,t,hours)];t.actualHours=hours;t.netAmount=hours*120; }), 'HYPERCARE-GRENZE'));
test('FEHLENDES_PHASE_TICKET blockiert externe Phase ohne Ticket', () => has(mutate((s) => { s.tickets.shift(); }), 'PHASE-VERTRAG'));
test('ZUSAETZLICHES_PHASE_TICKET wird blockiert', () => has(mutate((s) => { s.tickets.splice(3,0,structuredClone(s.tickets[0])); }), 'PHASE-VERTRAG'));
test('PHASE_REIHENFOLGE wird blockiert', () => has(mutate((s) => { s.tickets.find((ticket)=>ticket.id==='UABC-1').order=2; }), 'PHASE-VERTRAG'));
test('PHASE_WORKLOG blockiert direkte Abrechnung', () => has(mutate((s) => { s.tickets[0].worklogs=[worklog(s)]; }), 'ELTERN-WORKLOG'));
test('PHASE_EPIC blockiert Phasentitel als Epic', () => has(mutate((s) => { s.tickets.find((t)=>t.type==='epic').summary='Phase 1'; }), 'EPIC-PHASE'));
test('EPIC_WITHOUT_PHASE blockiert fehlende Phase-Elternbindung', () => has(mutate((s) => { s.tickets.find((t)=>t.type==='epic').parent=null; }), 'EPIC-PHASE'));
test('STORY_WITHOUT_PHASE blockiert Ergebnis ohne Phase', () => has(mutate((s) => { s.tickets.find((t)=>t.type==='story').phaseId=null; }), 'TICKET-PHASE'));
test('FALSE_PHASE_ROLLUP blockiert falsche Phasensumme', () => has(mutate((s) => { s.tickets[0].actualHours=23; }), 'PHASE-ROLLUP'));
test('MIGRATION_PHASE_TARGET blockiert semantisch falsches Phasenziel', () => has(mutate((s) => { s.ticketMigration.find((r) => r.sourceId === 'UABC-PHASE-1').targetId='UABC-19'; }), 'MIGRATIONSMAP'));
test('MIGRATION_DANGLING_TARGET blockiert unbekanntes aktives Ziel', () => has(mutate((s) => { s.ticketMigration.find((r) => r.targetKind === 'active-ticket').targetId='UABC-99'; }), 'MIGRATIONSMAP'));
test('AKTIVE_ALT_ID blockiert alte Ticket-ID in dependency', () => has(mutate((s) => { task(s).dependencies = ['TKT-UABC-35']; }), 'AKTIVE-ALT-ID'));
test('AKTIVE_ALT_ID blockiert alte Phasen-ID als parent', () => has(mutate((s) => { task(s).parent = 'UABC-PHASE-2'; }), 'AKTIVE-ALT-ID'));
test('AKTIVE_ALT_ID blockiert alte Ticket-ID in Seitenreferenz', () => has(mutate((s) => { s.pages[0].references = ['TKT-UABC-22']; }), 'AKTIVE-ALT-ID'));
test('fachlich gültige zusätzliche Ticketmenge wird dynamisch akzeptiert', () => { const copy=structuredClone(source);addDynamicTask(copy);assert.deepEqual(validateStory(copy,{checkFiles:false}),[]); });
test('unbekannte Ticketreferenz wird fail-closed abgelehnt', () => has(mutate((s) => { task(s).pageRefs=['PAGE-NICHT-DA']; }), 'UNBEKANNTE-TICKET-REFERENZ'));
test('Abhängigkeitsschleife wird fail-closed abgelehnt', () => has(mutate((s) => { const first=task(s);const second=s.tickets.find((ticket)=>ticket.type==='task'&&ticket.id!==first.id);first.dependencies=[second.id];second.dependencies=[first.id]; }), 'TICKET-ABHAENGIGKEITS-ZYKLUS'));
test('globale Akzeptanzschablone wird abgelehnt', () => has(mutate((s) => { s.tickets[1].acceptanceCriteria=structuredClone(s.tickets[0].acceptanceCriteria); }), 'ABNAHME-SCHABLONE'));
test('zukünftiges Gate darf nicht erledigt sein', () => has(mutate((s) => { const t=s.tickets.find((ticket)=>ticket.id==='UABC-50');t.status='done';t.closedAt='2026-07-13';t.statusHistory.push({status:'done',time:'2026-07-13',actorRef:'P-PILOT-LEAD-001',actorType:'human',actionRole:'Projektleitung'});t.acceptanceCriteria.forEach(criterion=>criterion.fulfilled=true);t.comments.push({id:'COM-UABC-50-CLOSE-TEST',type:'closing',time:'2026-07-13',role:'Projektleitung',actorRef:'P-PILOT-LEAD-001',actorType:'human',actionRole:'Projektleitung',text:'Evidence Test',evidenceRef:t.evidenceRefs[0]}); }), 'FUTURE-GATE-STATUS'));
test('bloß umbenannte CRONUS-Baseline ist kein eingerichteter Pilot', () => has(mutate((s) => { s.businessCentralPilotState.pilotConfigured=true;s.businessCentralPilotState.observedDisplayName=s.businessCentralPilotState.targetDisplayName; }), 'BC-PILOT-ZUSTAND'));
test('sprachlich beschädigte offene Form wird abgelehnt', () => has(mutate((s) => { s.tickets.find((ticket)=>ticket.id==='UABC-2').description='Die Phase endet erst nach soll geprüft werdener Prozess- und Abnahmeprobe und darf so nicht in den aktiven Vertrag gelangen.'; }), 'TICKET-TEXT'));
test('erfolgreich durchgeführte offene Arbeit wird abgelehnt', () => has(mutate((s) => { s.tickets.find((ticket)=>ticket.id==='UABC-49').description='Die VAT-Prüfung wurde erfolgreich durchgeführt, obwohl der aktive Pilot noch offen ist und keine Readback-Evidence besitzt.'; }), 'TICKET-TEXT'));
test('generisches Task-Abnahmekriterium wird abgelehnt', () => has(mutate((s) => { s.tickets.find((ticket)=>ticket.id==='UABC-39').acceptanceCriteria[0].criterion='Die Arbeit wird gemäß Beschreibung ausgeführt und mit Soll-/Ist-Readback dokumentiert.'; }), 'TASK-ABNAHME-KONKRET'));
test('generisches Story-Abnahmekriterium wird abgelehnt', () => has(mutate((s) => { s.tickets.find((ticket)=>ticket.id==='UABC-21').acceptanceCriteria[0].criterion='Die Story ist fachlich mit der verantwortlichen Rolle abgestimmt und als überprüfbares Ergebnis beschrieben.'; }), 'ABNAHME-KONKRET'));
test('erfolgsbehauptendes Deliverable eines offenen Tickets wird abgelehnt', () => has(mutate((s) => { s.tickets.find((ticket)=>ticket.id==='UABC-46').deliverable='Bestandene UAT- und Mock-Cutover-Entscheidung'; }), 'TICKET-LIEFERERGEBNIS-STATUS'));
