import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { validateStory } from '../../scripts/validate-project-story.mjs';

const source = JSON.parse(readFileSync('evidence/simulation/project-story.json', 'utf8'));
const mutate = (fn) => { const copy = structuredClone(source); fn(copy); return validateStory(copy, { checkFiles: false }); };
const has = (errors, code) => assert.equal(errors.some((error) => error.startsWith(`${code}:`)), true, code);
const task = (story) => story.tickets.find((ticket) => ticket.type === 'task');

test('positive Vollstory besteht', () => assert.deepEqual(validateStory(source, { checkFiles: true }), []));
test('NESTED_TYPE erkennt Worklogtyp', () => has(mutate((s) => { task(s).worklogs[0].hours = '6'; }), 'WORKLOG-NESTED-TYP'));
test('UNAUTHORIZED_PROPERTY erkennt unerlaubte Top-Level-Eigenschaft', () => has(mutate((s) => { s.unexpected = true; }), 'UNERLAUBTE-EIGENSCHAFT'));
test('CLOSING_COMMENT erkennt fehlenden Abschlusskommentar', () => has(mutate((s) => { task(s).comments.pop(); }), 'ABSCHLUSS-KOMMENTAR-FEHLT'));
test('WORKLOG_SUM erkennt falsche Summe', () => has(mutate((s) => { task(s).worklogs[0].hours = 7; }), 'WORKLOG-SUMME'));
test('STATUS_TIME_TRAVEL erkennt zeitliche Rückreise', () => has(mutate((s) => { task(s).closedAt = '2020-01-01'; }), 'STATUS-ZEITREISE'));
test('TERMINAL_STATUS erkennt abweichenden Endstatus', () => has(mutate((s) => { s.tickets[0].statusHistory[s.tickets[0].statusHistory.length - 1] = 'closed'; }), 'ENDSTATUS-ABWEICHUNG'));
test('PAGE_CYCLE erkennt Seitenzyklus', () => has(mutate((s) => { s.pages[0].parent = 'PAGE-UABC-010'; }), 'SEITE-ZYKLUS'));
test('PAGE_METADATA erkennt verschachtelten Metadatenfehler', () => has(mutate((s) => { s.pages[0].version = '3'; }), 'SEITE-METADATEN-TYP'));
test('UNKNOWN_TIMELINE_REFERENCE erkennt unbekannte Ticketreferenz', () => has(mutate((s) => { s.timeline[0].tickets = ['TKT-NOT-FOUND']; }), 'UNBEKANNTE-TIMELINE-REFERENZ'));
test('OPEN_P1_P2 erkennt offenes P1', () => has(mutate((s) => { s.controls.openP1 = 1; }), 'OFFENES-P1-P2'));
test('UNKNOWN_RELATION erkennt unbekannten Relationstyp', () => has(mutate((s) => { s.relations = [{ type: 'unknown', from: 'TKT-UABC-22', to: 'TKT-UABC-23', inverse: 'TKT-UABC-23->TKT-UABC-22' }]; }), 'UNBEKANNTE-RELATION'));
test('INVERSE_RELATION erkennt falsche inverse Kante', () => has(mutate((s) => { s.relations = [{ type: 'blocks', from: 'TKT-UABC-22', to: 'TKT-UABC-23', inverse: 'wrong' }]; }), 'INVERSE-RELATION'));
test('DUPLICATE_SOURCE_PATH erkennt echten doppelten Quellpfad', () => has(mutate((s) => { s.pages[2].sourcePath = s.pages[1].sourcePath; }), 'SEITE-DOPPELTER-PFAD'));
test('NESTED_ADDITIONAL_PROPERTY erkennt unerlaubte Kommentareigenschaft', () => has(mutate((s) => { task(s).comments[0].unexpected = true; }), 'UNERLAUBTE-EIGENSCHAFT'));
test('PAGE_FILE_METADATA erkennt Abweichung aus injiziertem Leser', () => has(validateStory(source, { checkFiles: false, metadataReader: () => ({ id: 'falsch', parent: null, version: 99, status: 'falsch' }) }), 'SEITE-METADATEN-ABWEICHUNG'));
test('STATUSHISTORY_TIME_TRAVEL erkennt Zeitreise in strukturierter Historie', () => has(mutate((s) => { s.tickets[0].statusHistory = [{ status: 'created', time: '2026-08-20' }, { status: 'in-progress', time: '2026-08-19' }, { status: 'done', time: '2026-08-20' }]; }), 'STATUSHISTORY-ABWEICHUNG'));
test('WORKLOG_COST erkennt falsche globale Kosten', () => has(mutate((s) => { task(s).worklogs[0].netAmount = 0; }), 'WORKLOG-NESTED-TYP'));
test('TIMELINE_UNKNOWN_EVIDENCE erkennt unbekannte Evidence', () => has(mutate((s) => { s.timeline[0].evidence = 'EVIDENCE-NOT-FOUND'; }), 'UNBEKANNTE-TIMELINE-REFERENZ'));
test('TIMELINE_UNKNOWN_SESSION erkennt unbekannte BC-Sitzung', () => has(mutate((s) => { s.timeline[0].sessions = ['SESSION-NOT-FOUND']; }), 'UNBEKANNTE-TIMELINE-REFERENZ'));
test('TIMELINE_UNKNOWN_DECISION erkennt unbekannte Entscheidung', () => has(mutate((s) => { s.timeline[0].decision = 'DECISION-NOT-FOUND'; }), 'UNBEKANNTE-TIMELINE-REFERENZ'));
test('TIMELINE_OUTSIDE_WINDOW erkennt Zeit ausserhalb Projektzeitraum', () => has(mutate((s) => { s.timeline[0].time = '2027-01-01'; }), 'TIMELINE-GRENZE'));
test('REFERENCED_OPEN_P1 erkennt tatsächlich offenes P1-Ticket', () => has(mutate((s) => { s.tickets.find((t) => t.id === s.hypercare[0].ticket).status = 'in-progress'; }), 'OFFENES-P1-P2'));
test('INVERSE_MISSING erkennt fehlende Rückkante', () => has(mutate((s) => { s.relations = s.relations.filter((r) => !(r.type === 'references' && r.from === 'UABC-32')); }), 'INVERSE-RELATION'));
test('STRING_STATUSHISTORY wird nicht als kanonisch akzeptiert', () => has(mutate((s) => { s.tickets[0].statusHistory = ['created','in-progress','done']; }), 'STATUSHISTORY-ABWEICHUNG'));
test('FEHLENDE_WORKLOG_KOSTEN werden abgelehnt', () => has(mutate((s) => { delete task(s).worklogs[0].netAmount; }), 'WORKLOG-NESTED-TYP'));
test('FEHLENDE_HYPERCARE_EVIDENCE wird abgelehnt', () => has(mutate((s) => { delete s.hypercare[0].evidence; }), 'HYPERCARE-RECORD'));
test('GRAPH_WAISE erkennt eine unbekannte Domänenkante', () => has(mutate((s) => { s.relations.push({ type: 'references', from: 'PAGE-NOT-FOUND', to: 'TKT-UABC-22' }); }), 'RELATION-WAISE'));
test('GRAPH_DUPLIKAT erkennt doppelte Kante', () => has(mutate((s) => { s.relations.push(structuredClone(s.relations[0])); }), 'RELATION-DOPPELT'));
test('PAGE_SPACE erkennt fehlende Space-Zuordnung', () => has(mutate((s) => { delete s.pages[0].spaceId; }), 'SEITE-METADATEN-TYP'));
test('PAGE_SPACE_PARENT erkennt Space-uebergreifenden Parent', () => has(mutate((s) => { s.pages.find((p) => p.id === 'PAGE-UABC-010').parent = 'PAGE-UABC-090'; }), 'SEITE-SPACE-PARENT'));
test('PAGE_ORDER erkennt doppelte Reihenfolge im Space', () => has(mutate((s) => { s.pages.find((p) => p.id === 'PAGE-UABC-010').order = 0; }), 'SEITE-REIHENFOLGE'));
test('PAGE_ROOT erkennt fehlende deklarierte Space-Wurzel', () => has(mutate((s) => { s.pages.find((p) => p.id === 'PAGE-UABC-090').parent = 'PAGE-UABC-000'; }), 'SEITE-WURZEL'));
test('TICKET_TYPE_MISSING erkennt fehlenden kanonischen Typ', () => has(mutate((s) => { delete s.tickets[0].type; }), 'TICKET-TYP'));
test('TICKET_TYPE_UNKNOWN erkennt unbekannten kanonischen Typ', () => has(mutate((s) => { s.tickets[0].type = 'ableitung-aus-titel'; }), 'TICKET-TYP'));
test('TICKET_PARENT_TYPE erkennt inkonsistenten Parent-Typ', () => has(mutate((s) => { s.tickets.find((t) => t.id === 'UABC-34').parent = 'UABC-47'; }), 'TICKET-PARENT-TYP'));
test('TICKET_PARENT_TYPE erkennt Parent an Epic', () => has(mutate((s) => { s.tickets[0].parent = 'UABC-50'; }), 'TICKET-PARENT-TYP'));
test('ELTERN_WORKLOG blockiert fakturierbaren Worklog auf Epic', () => has(mutate((s) => { s.tickets[0].worklogs = [structuredClone(task(s).worklogs[0])]; }), 'ELTERN-WORKLOG'));
test('TASK_BILLABLE blockiert nicht abrechenbaren Phasen-Task', () => has(mutate((s) => { task(s).billable = false; }), 'TASK-ABRECHNUNG'));
test('TASK_PARENT blockiert Task ohne Story- oder Bug-Elternteil', () => has(mutate((s) => { task(s).parent = 'UABC-4'; }), 'TICKET-PARENT-TYP'));
test('DOPPELTES_WORKLOG wird blockiert', () => has(mutate((s) => { task(s).worklogs.push(structuredClone(task(s).worklogs[0])); }), 'WORKLOG-FEHLT'));
test('HYPERCARE_GRENZE blockiert mehr als zehn Stunden', () => has(mutate((s) => { const t=s.tickets.find((x)=>x.id==='UABC-47'); t.actualHours=11; t.netAmount=1320; t.worklogs[0].hours=11; t.worklogs[0].netAmount=1320; }), 'HYPERCARE-GRENZE'));
test('FEHLENDES_PHASE_TICKET blockiert externe Phase ohne Ticket', () => has(mutate((s) => { s.tickets.shift(); }), 'PHASE-VERTRAG'));
test('ZUSAETZLICHES_PHASE_TICKET wird blockiert', () => has(mutate((s) => { s.tickets.splice(3,0,structuredClone(s.tickets[0])); }), 'PHASE-VERTRAG'));
test('PHASE_REIHENFOLGE wird blockiert', () => has(mutate((s) => { [s.tickets[0],s.tickets[1]]=[s.tickets[1],s.tickets[0]]; }), 'PHASE-VERTRAG'));
test('PHASE_WORKLOG blockiert direkte Abrechnung', () => has(mutate((s) => { s.tickets[0].worklogs=[structuredClone(task(s).worklogs[0])]; }), 'ELTERN-WORKLOG'));
test('PHASE_EPIC blockiert Phasentitel als Epic', () => has(mutate((s) => { s.tickets.find((t)=>t.type==='epic').summary='Phase 1'; }), 'EPIC-PHASE'));
test('EPIC_WITHOUT_PHASE blockiert fehlende Phase-Elternbindung', () => has(mutate((s) => { s.tickets.find((t)=>t.type==='epic').parent=null; }), 'EPIC-PHASE'));
test('STORY_WITHOUT_PHASE blockiert Ergebnis ohne Phase', () => has(mutate((s) => { s.tickets.find((t)=>t.type==='story').phaseId=null; }), 'TICKET-PHASE'));
test('FALSE_PHASE_ROLLUP blockiert falsche Phasensumme', () => has(mutate((s) => { s.tickets[0].actualHours=23; }), 'PHASE-ROLLUP'));
