import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { buildProjection, INDEX_PATH, MAP_PATH, PROVENANCE_PATH } from '../../scripts/generate-setup-wave-1-export.mjs';
import { lfBytes } from '../../scripts/generate-spectra-0.10-integration.mjs';
import { validateAdapterProvenance, validateExport, validateProjection } from '../../scripts/validate-setup-wave-1-export.mjs';
test('Setup-Wave-1-Projektion ist deterministisch und positivgelistet', () => { const one = buildProjection(); const two = buildProjection(); assert.deepEqual(one, two); assert.deepEqual(validateExport(), []); });
test('Projektion bleibt schreibgeschuetzt', () => { const projection = buildProjection(); assert.equal(projection.writesAuthorized, false); assert.equal(projection.writeGate.noGoSteps.length, 17); assert.equal(projection.provenance.some(({ path }) => /(?:[A-Za-z]:|^\/|\\)/.test(path)), false); });
test('Standard-CRONUS-Demo-Baseline bleibt strukturiert vom Pilot-Soll getrennt', () => { const projection = buildProjection(); assert.deepEqual(projection.configurationState, { baselineKind: 'standard-cronus-demo', pilotConfigured: false, writesApplied: false, readbackStatus: 'pending', technicalCompanyName: 'UABC-BASIC-DE', internalCompanyId: null, observedDisplayName: 'Universaarl GmbH', targetDisplayName: 'Universaarl GmbH (BC Basic Pilot)', targetDecision: 'pending-wave-0-evidence', resetDecision: 'pending-resetpoint-evidence' }); });
test('unspezifische CRONUS-Klassifikation wird abgelehnt', () => { const projection = buildProjection(); const schema = JSON.parse(fs.readFileSync('governance/schemas/setup-wave-1-projection.schema.json', 'utf8')); projection.configurationState.baselineKind = 'cronus-demo'; const errors = validateProjection(projection, schema); assert.ok(errors.some((error) => error.startsWith('/configurationState/baselineKind '))); assert.ok(errors.includes('CRONUS-PILOT-TRENNUNG')); });
test('bloße Umbenennung darf keine Pilotkonfiguration behaupten', () => { const projection = buildProjection(); const schema = JSON.parse(fs.readFileSync('governance/schemas/setup-wave-1-projection.schema.json', 'utf8')); projection.configurationState.pilotConfigured = true; projection.configurationState.observedDisplayName = projection.configurationState.targetDisplayName; assert.ok(validateProjection(projection, schema).includes('CRONUS-PILOT-TRENNUNG')); });
test('Projektion enthaelt keine Geheimnis- oder Authfelder', () => { const text = JSON.stringify(buildProjection()); assert.doesNotMatch(text, /password|token|secret|session|authorization/i); });
test('Manipulierte Schreibfreigabe wird fail-closed abgelehnt', () => { const projection = buildProjection(); const schema = JSON.parse(fs.readFileSync('governance/schemas/setup-wave-1-projection.schema.json', 'utf8')); projection.writesAuthorized = true; assert.ok(validateProjection(projection, schema).includes('SCHREIBSPERRE')); });
test('Veraltete Adapter-Provenienz gegen geaenderte Exportmap wird fail-closed abgelehnt', () => {
  const indexBytes = lfBytes(fs.readFileSync(INDEX_PATH));
  const map = JSON.parse(fs.readFileSync(MAP_PATH, 'utf8'));
  const provenance = JSON.parse(fs.readFileSync(PROVENANCE_PATH, 'utf8'));
  const changedMapBytes = Buffer.from(`${JSON.stringify({ ...map, artifacts: map.artifacts.map((artifact, index) => index === 0 ? { ...artifact, selector: 'gezielt-veraendert' } : artifact) }, null, 2)}\n`, 'utf8');
  const errors = validateAdapterProvenance({ provenance, indexBytes, mapBytes: changedMapBytes });
  assert.ok(errors.some((error) => error.startsWith('ADAPTER_PROJEKTIONS_DIGEST:')), errors.join('\n'));
});
